module:
  hugoVersion:
    min: "0.61.0"
  mounts:
    - source: layouts
      target: layouts
    - source: partials
      target: layouts/partials/tnd-headers

mediaTypes:
  text/netlify:
    delimiter: ''
    suffixes:
      - ''

outputFormats:
  tnd_headers_netlify:
    baseName: _headers
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true